SOURCES += \
	../NAF/Qtl2/Variant.cpp \
	../NAF/Qtl2/QtlWidget.cpp \
	../NAF/Qtl2/QtlUrl.cpp \
	../NAF/Qtl2/QtlTreeWidgetItem.cpp \
	../NAF/Qtl2/QtlTreeWidget.cpp \
	../NAF/Qtl2/QtlTreeView.cpp \
	../NAF/Qtl2/QtlToolButton.cpp \
	../NAF/Qtl2/QtlToolBox.cpp \
	../NAF/Qtl2/QtlToolBar.cpp \
	../NAF/Qtl2/QtlTime.cpp \
	../NAF/Qtl2/QtlTextEdit.cpp \
	../NAF/Qtl2/QtlTabWidget.cpp \
	../NAF/Qtl2/QtlTabBar.cpp \
	../NAF/Qtl2/QtlStringList.cpp \
	../NAF/Qtl2/QtlString.cpp \
	../NAF/Qtl2/QtlStatusBar.cpp \
	../NAF/Qtl2/QtlStackedWidget.cpp \
	../NAF/Qtl2/QtlSizePolicy.cpp \
	../NAF/Qtl2/QtlSize.cpp \
	../NAF/Qtl2/QtlShortcut.cpp \
	../NAF/Qtl2/QtlScrollArea.cpp \
	../NAF/Qtl2/QtlRegion.cpp \
	../NAF/Qtl2/QtlRect.cpp \
	../NAF/Qtl2/QtlPushButton.cpp \
	../NAF/Qtl2/QtlProgressBar.cpp \
	../NAF/Qtl2/QtlPolygon.cpp \
	../NAF/Qtl2/QtlPoint.cpp \
	../NAF/Qtl2/QtlPixmap.cpp \
	../NAF/Qtl2/QtlPen.cpp \
	../NAF/Qtl2/QtlPalette.cpp \
	../NAF/Qtl2/QtlPainterPath.cpp \
	../NAF/Qtl2/QtlMessageBox.cpp \
	../NAF/Qtl2/QtlMenuBar.cpp \
	../NAF/Qtl2/QtlMenu.cpp \
	../NAF/Qtl2/QtlMatrix.cpp \
	../NAF/Qtl2/QtlLineEdit.cpp \
	../NAF/Qtl2/QtlLine.cpp \
	../NAF/Qtl2/QtlLCDNumber.cpp \
	../NAF/Qtl2/QtlKeySequence.cpp \
	../NAF/Qtl2/QtlImage.cpp \
	../NAF/Qtl2/QtlHeaderView.cpp \
	../NAF/Qtl2/QtlGroupBox.cpp \
	../NAF/Qtl2/QtlFrame.cpp \
	../NAF/Qtl2/QtlFontMetrics.cpp \
	../NAF/Qtl2/QtlFontInfo.cpp \
	../NAF/Qtl2/QtlFont.cpp \
	../NAF/Qtl2/QtlFileDialog.cpp \
	../NAF/Qtl2/QtlDialog.cpp \
	../NAF/Qtl2/QtlDial.cpp \
	../NAF/Qtl2/QtlDateTime.cpp \
	../NAF/Qtl2/QtlDate.cpp \
	../NAF/Qtl2/QtlColor.cpp \
	../NAF/Qtl2/QtlCheckBox.cpp \
	../NAF/Qtl2/QtlChar.cpp \
	../NAF/Qtl2/QtlButtonGroup.cpp \
	../NAF/Qtl2/QtlBrush.cpp \
	../NAF/Qtl2/QtlBitmap.cpp \
	../NAF/Qtl2/QtlBitArray.cpp \
	../NAF/Qtl2/QtlActionGroup.cpp \
	../NAF/Qtl2/QtlAction.cpp \
	../NAF/Qtl2/QtlAbstractSlider.cpp \
	../NAF/Qtl2/QtlAbstractButton.cpp \
	../NAF/Qtl2/QltIcon.cpp \
	../NAF/Qtl2/Objects.cpp \
	../NAF/Qtl2/QtlPrinter.cpp \
	../NAF/Qtl2/QtlPainter.cpp \
	../NAF/Qtl2/QtlTextOption.cpp \
	../NAF/Qtl2/QtlTableView.cpp \
	../NAF/Qtl2/QtlAbstractItemView.cpp \
	../NAF/Qtl2/QtlTableWidgetItem.cpp \
	../NAF/Qtl2/QtlTableWidget.cpp \
	../NAF/Qtl2/QtlCustomWidget.cpp

HEADERS  += \
	../NAF/Qtl2/Variant.h \
	../NAF/Qtl2/QtlWidget.h \
	../NAF/Qtl2/QtlUrl.h \
	../NAF/Qtl2/QtlTreeWidgetItem.h \
	../NAF/Qtl2/QtlTreeWidget.h \
	../NAF/Qtl2/QtlTreeView.h \
	../NAF/Qtl2/QtlToolButton.h \
	../NAF/Qtl2/QtlToolBox.h \
	../NAF/Qtl2/QtlToolBar.h \
	../NAF/Qtl2/QtlTime.h \
	../NAF/Qtl2/QtlTextEdit.h \
	../NAF/Qtl2/QtlTabWidget.h \
	../NAF/Qtl2/QtlTabBar.h \
	../NAF/Qtl2/QtlStringList.h \
	../NAF/Qtl2/QtlString.h \
	../NAF/Qtl2/QtlStatusBar.h \
	../NAF/Qtl2/QtlStackedWidget.h \
	../NAF/Qtl2/QtlSizePolicy.h \
	../NAF/Qtl2/QtlSize.h \
	../NAF/Qtl2/QtlShortcut.h \
	../NAF/Qtl2/QtlScrollArea.h \
	../NAF/Qtl2/QtlRegion.h \
	../NAF/Qtl2/QtlRect.h \
	../NAF/Qtl2/QtlPushButton.h \
	../NAF/Qtl2/QtlProgressBar.h \
	../NAF/Qtl2/QtlPolygon.h \
	../NAF/Qtl2/QtlPoint.h \
	../NAF/Qtl2/QtlPixmap.h \
	../NAF/Qtl2/QtlPen.h \
	../NAF/Qtl2/QtlPalette.h \
	../NAF/Qtl2/QtlPainterPath.h \
	../NAF/Qtl2/QtlMessageBox.h \
	../NAF/Qtl2/QtlMenuBar.h \
	../NAF/Qtl2/QtlMenu.h \
	../NAF/Qtl2/QtlMatrix.h \
	../NAF/Qtl2/QtlLineEdit.h \
	../NAF/Qtl2/QtlLine.h \
	../NAF/Qtl2/QtlLCDNumber.h \
	../NAF/Qtl2/QtlKeySequence.h \
	../NAF/Qtl2/QtlImage.h \
	../NAF/Qtl2/QtlIcon.h \
	../NAF/Qtl2/QtlHeaderView.h \
	../NAF/Qtl2/QtlGroupBox.h \
	../NAF/Qtl2/QtlFrame.h \
	../NAF/Qtl2/QtlFontMetrics.h \
	../NAF/Qtl2/QtlFontInfo.h \
	../NAF/Qtl2/QtlFont.h \
	../NAF/Qtl2/QtlFileDialog.h \
	../NAF/Qtl2/QtlDialog.h \
	../NAF/Qtl2/QtlDial.h \
	../NAF/Qtl2/QtlDateTime.h \
	../NAF/Qtl2/QtlDate.h \
	../NAF/Qtl2/QtlColor.h \
	../NAF/Qtl2/QtlCheckBox.h \
	../NAF/Qtl2/QtlChar.h \
	../NAF/Qtl2/QtlButtonGroup.h \
	../NAF/Qtl2/QtlBrush.h \
	../NAF/Qtl2/QtlBitmap.h \
	../NAF/Qtl2/QtlBitArray.h \
	../NAF/Qtl2/QtlActionGroup.h \
	../NAF/Qtl2/QtlAction.h \
	../NAF/Qtl2/QtlAbstractSlider.h \
	../NAF/Qtl2/QtlAbstractButton.h \
	../NAF/Qtl2/Objects.h \
	../NAF/Qtl2/QtlPrinter.h \
	../NAF/Qtl2/QtlPainter.h \
	../NAF/Qtl2/QtlTextOption.h \
	../NAF/Qtl2/QtlTableView.h \
	../NAF/Qtl2/QtlAbstractItemView.h \
	../NAF/Qtl2/QtlTableWidgetItem.h \
	../NAF/Qtl2/QtlTableWidget.h \
	../NAF/Qtl2/QtlCustomWidget.h

